language: php

sudo: false
dist: trusty

git:
  depth: 3

notifications:
  email: false
  slack:
    secure: Ln15qc2azVPfgiWdAU7u/Amd36edkj6LbPLfD4MJNiv4iKJz1CC8t80wSAvcSzZ+f/o/7W9V59HqIf4K+/Ner2oEBRuVJqMsFEKm7D9WacoAv5g4k0C+zagFhZfKXKfu7Kifz8zFtCSoY8FYjmXGcEANd5oPfmweJbymGtNKJKKnp0T2UfQqjuvXQslgL+Z5b2oyyqlYiHk+erd4NXEQp3G7910fMRfdVwmu5FZ6CV70FJvPAr4wvldydaMV6rkHV2aU5zBwcWM/UsfUevp+mPxGpX+75QnenjZQmR7YkSx4vTxA1PeY4oEvruv0zLEBrX/mGba8gYI8Q/8PaD86fy6e8pY9hxQSVLP7Fr37fsH2RZZ8ZxjrWugEleGSL55kTd//zZdiqxCDCscIfpAskSkN9mmmdEguuP6KZFWJ4KRIc04YA2xk/5nVtBoWT9BgfmHP92PPaX1T4vPykM8uBsyN1JD6XoNp6PNak1iLJBJ+8BmpuLryjBf4knpqVQDd8+abL40PZihwIJZnJLjdv1o1JV5n4TaWqe28TIVij73BYY1VHEFuueBskpW4Ttn2I9kcHxUQWusZ1msAzirvnKg9avfpRuCH06LM/rAWOgpdSGZsmR0mtPzV0VoaJg4aUaDlgNlu2e506RpA2yBTmS4LWqiXwm+daDOkZSnqMzU=

branches:
  only:
    - master
    - "/^v[0-9\\.]+/"

cache:
  yarn: true
  directories:
    - "${HOME}/.composer/cache"
    - node_modules

stages:
  - name: check
    if: branch = master and tag IS blank and type IN (pull_request, api, cron)

before_script:
  - git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci
  - bash travis-ci/bin/prepare.sh

jobs:
  fast_finish: true
  include:
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpcs.sh
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpmd.sh
