language: php

sudo: false
dist: trusty

git:
  depth: 3

notifications:
  email: false
  slack:
    secure: Ln15qc2azVPfgiWdAU7u/Amd36edkj6LbPLfD4MJNiv4iKJz1CC8t80wSAvcSzZ+f/o/7W9V59HqIf4K+/Ner2oEBRuVJqMsFEKm7D9WacoAv5g4k0C+zagFhZfKXKfu7Kifz8zFtCSoY8FYjmXGcEANd5oPfmweJbymGtNKJKKnp0T2UfQqjuvXQslgL+Z5b2oyyqlYiHk+erd4NXEQp3G7910fMRfdVwmu5FZ6CV70FJvPAr4wvldydaMV6rkHV2aU5zBwcWM/UsfUevp+mPxGpX+75QnenjZQmR7YkSx4vTxA1PeY4oEvruv0zLEBrX/mGba8gYI8Q/8PaD86fy6e8pY9hxQSVLP7Fr37fsH2RZZ8ZxjrWugEleGSL55kTd//zZdiqxCDCscIfpAskSkN9mmmdEguuP6KZFWJ4KRIc04YA2xk/5nVtBoWT9BgfmHP92PPaX1T4vPykM8uBsyN1JD6XoNp6PNak1iLJBJ+8BmpuLryjBf4knpqVQDd8+abL40PZihwIJZnJLjdv1o1JV5n4TaWqe28TIVij73BYY1VHEFuueBskpW4Ttn2I9kcHxUQWusZ1msAzirvnKg9avfpRuCH06LM/rAWOgpdSGZsmR0mtPzV0VoaJg4aUaDlgNlu2e506RpA2yBTmS4LWqiXwm+daDOkZSnqMzU=

branches:
  only:
    - master
    - "/^v[0-9\\.]+/"

cache:
  yarn: true
  directories:
    - "${HOME}/.composer/cache"
    - node_modules
    - "${TRAVIS_BUILD_DIR}/.plugin"
    - "${TRAVIS_BUILD_DIR}/.work/cache"

stages:
  - name: check
    if: branch = master and tag IS blank and type IN (pull_request, api, cron)
  - name: deploy
    if: tag IS present

before_script:
  - git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci
  - bash travis-ci/bin/prepare.sh

jobs:
  fast_finish: true
  include:
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpcs.sh
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpmd.sh


    - stage: deploy
      language: node_js
      node_js: '11'
      dist: trusty
      script: skip
      before_deploy:
        - source travis-ci/bin/deploy/env.sh
        - bash travis-ci/bin/deploy/create.sh
      deploy:
        provider: releases
        skip_cleanup: true
        name: ${RELEASE_TITLE}
        tag_name: ${RELEASE_TAG}
        api_key:
          secure: RXfkDhKrq8Pocwr8xEqm7WTEDaYEnh+zFy3uyjL+BUYB8QUce98y9n/tkhg4Wn1nM3YWQeMEChzINWEJydfWOjK6Zxvq8k127vSkfFEISvymWGQOltBPYUjH/y8dWDwxX8sZsMCys6UG1FAc4mWPE2DcPn/G8dJTQdSOupB2PdJwBatybfOF8HHBQuf1vMhcnt/wLeE8685KtmuHKtCzW96IKbw4WWU1on/fCH7dGld7wnY/ywNLmPYQHXXrlP/X2qzGZkQ9b1pjs+R1XILHIRbbezrgSBA6dRwnt4GuNFk2DqdY3pYoeDIdrrlZr5IC95iAlynDv2kSwCHsQZ8JEUwUmQSoVb30f/e4zLLQzMXB7N9725+mjJtBzYWQch9mQqkjaMSM50udSvPPH4diKmFwcxXK4Jk8YT8JxRA+MO9M0FJTGOCJfqdbesD6UACbarI30y1l2awe86emSvoedreBOTF2q6xFKAAqW8RBbBbRXtKBG0l2Pn9VU4VW435jy8Ut+dZAJ0zslATa3aq0qM+6sNOHvl5ksmEyVf8YgnbxJfegZ2GkChbu0AqdePHhulKIlwlgRSdXoIp/WlwrZFbUFp7vW8M26WaZzY2dLkUdM3tCNtcSge04vu2hx7S6OLRlQyTV/gKhbHiWEl9ro4uOjLwkSCjNfBPds+ry8K4=
        file: ${RELEASE_FILE}
        body: ${RELEASE_BODY}
        overwrite: true
        on:
          tags: true
