on:
  schedule:
    - cron: 0 13 * * 4
  repository_dispatch:
    types: [sync-workflows]
  workflow_dispatch:

name: Sync workflows
jobs:
  release:
    name: Sync workflows
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Sync workflows
        uses: technote-space/create-pr-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXECUTE_COMMANDS: |
            rm -rdf .github/workflows/.tmp
            mkdir -p .github/workflows/.tmp
            git clone --depth=1 https://github.com/technote-space/github-actions-workflows.git .github/workflows/.tmp/workflows

            bash .github/workflows/.tmp/workflows/wp-plugin/copy.sh releases php-lint
            sed -i "s/WP_VERSION: \[.\+$/WP_VERSION: ['latest', '5.0']/" .github/workflows/ci.yml

            rm -rdf .github/workflows/.tmp
          COMMIT_MESSAGE: 'chore: sync workflows'
          PR_BRANCH_PREFIX: chore/
          PR_BRANCH_NAME: 'chore-sync-workflows'
          PR_TITLE: 'chore: sync workflows'
          ONLY_DEFAULT_BRANCH: true
